boats/app_boats/urls.py
from django.conf.urls import url, include
from . import views

urlpatterns = [
    url('getPath', views.getPath),
    url(r'^$', views.BoatsView, name='boats'),
]

boats/boats/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.apps import apps
login_name = apps.get_app_config('login').verbose_name
app_boats_name = apps.get_app_config('app_boats').verbose_name
alerts_name = apps.get_app_config('app_alerts').verbose_name

urlpatterns = [
    url(r'^', include(('login.urls', login_name), namespace='login')),
    url(r'^boats', include(('app_boats.urls', app_boats_name), namespace='app_boats')),
    url(r'alerts/', include(('app_alerts.urls', alerts_name), namespace='app_alerts'))
]

boats/login/urls.py
from django.contrib.auth import views as auth_views
from django.views.generic.base import TemplateView
from django.conf.urls import url
from django.contrib import admin
from login import views

urlpatterns = [
    url(r'^$', views.homepage, {'template_name':'home.html'}, name='home'),
    url(r'home^$', views.homepage, {'template_name':'home.html'}, name='home'),
    url(r'^signup/$', views.signup, name='signup'),
    url(r'^login/$', views.custom_login, {'template_name': 'login.html'}, name='login'),
    url(r'^logout/$', auth_views.logout, {'template_name': 'logged_out.html'}, name='logout'),
    url(r'^settings/$', views.modify_user,  name='settings'),
    url(r'^change_password$',
        auth_views.password_change,
        {'template_name':'change_password.html',
            'post_change_redirect':'login:password_reset_done'},
        name='change_password'),
    url(r'^password_reset_done/$',
        TemplateView.as_view(template_name='password_reset_done.html'),
        name='password_reset_done'),
]

boats/app_boats/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from login.models import Profile


class Direction(models.Model):
    user = models.ForeignKey('login.Profile',
                            on_delete=models.PROTECT)
    start = models.CharField(max_length=100)
    end = models.CharField(max_length=100)
    date = models.DateTimeField(auto_now_add=True, auto_now=False,
                                verbose_name="Date de parution")

boats/app_boats/views.py
from django.contrib.auth import login, authenticate
from django.contrib.auth.forms import UserCreationForm
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse
import requests
import json
from .stubApiModule import generatePathDico
from django.contrib.auth.decorators import login_required
def getPath(request):
  print('ICI')
  if request.method == 'GET':
    if 'long1' in request.GET and 'lat1' in request.GET and 'long2' in request.GET and 'lat2' in request.GET:
      long1 = float(request.GET.get('long1'))
      lat1 = float(request.GET.get('lat1'))
      long2 = float(request.GET.get('long2'))
      lat2 = float(request.GET.get('lat2'))
      STUB = False
      aStarOption = (request.GET.get('aStar'))
      if STUB:
        dico = generatePathDico(lat1, long1, lat2, long2)
        print(dico)
        return JsonResponse(dico, safe=False)
      else:
        print(long1, lat1, " ; ", long2, lat2)
        if aStarOption == "shortest":
          url = "http://10.20.28.81:5000/astar"
        elif aStarOption == "safer":
          url = "http://10.20.28.81:5000/astarDensity"

        # payload = {'start_long': start_long, 'start_lat': start_lat, 'end_long': end_long, 'end_lat': end_lat}
        payload = {'start_long': str(long1), 'start_lat': str(lat1), 'end_long': str(long2), 'end_lat': str(lat2)}

        r = requests.get(url, params=payload)
        dico = json.loads(r.text)
        return JsonResponse(json.loads(r.text), safe=False)

@login_required
def BoatsView(request):
  user=request.user
  print(user)
  return render(request, 'map.html',locals())

boats/boats/views.py
from django.shortcuts import render, redirect

boats/app_boats/templates/boats.html
{% extends 'base.html' %}

{% block title %}Login{% endblock %}
    <head>
        <meta charset="utf-8" />
        <title>Marquage du texte</title>
        <link rel="stylesheet" type="text/css" href="mystyle.css">
    </head>

{% block content %}
  <h2>BOATS BOATS BOATS</h2>

<!--   {% if response %}
  	<p>{{response}}</p>
  {% endif %}

  <form method="get">
	{% csrf_token %}
	{{ form.as_p }}
	<button type="submit">Request</button>
    </form>
 -->
    <body>
        <p>Saisissez votre itinéraire</p>
        <p>
            <label for="depart">Départ</label> <input type="text" name="depart" id="depart" placeholder="long,lat" />
            <label for="destination" >Destination</label> <input type="text" name="destination" id="destination" placeholder="34.65,78.59" />
            <input type="button" id="getPath" value="get Path !" />
        </p>

        <!-- <script src="submit.js"></script> -->

        <script>

//Recupère les élements sur la page 
var depart=document.getElementById("depart");
var destination=document.getElementById("destination");
var button=document.getElementById("getPath");
button.addEventListener("click", function(){
    console.log("Depart:"+depart.value);
    coord1=stringToCoordinate(depart.value);
    console.log("Destination:"+destination.value);
    coord2=stringToCoordinate(destination.value);
    params=coordToGetParams(coord1,coord2)
    //    alert(params);

    var xhr = new XMLHttpRequest(); 
    xhr.responseType="json";
    xhr.onreadystatechange = function() {
        if (xhr.readyState == 4 && (xhr.status == 200 || xhr.status == 0)) {
            console.log(xhr.response);
            alert(xhr.response);
        }
    };
    xhr.open("GET", "http://localhost:8000/boats"+params, true);
    xhr.send(params);
});




function stringToCoordinate(string) {
    var coord=string.split(",");
    return (coord)
}

function coordToGetParams(coord1,coord2) {
    var params="?long1="+coord1[0]
    params+="&lat1="+coord1[1]
    params+="&long2="+coord2[1]
    params+="&lat2="+coord2[1]
    return (params)
}
</script>

    </body>
<!-- </html> -->
{% endblock %}

boats/app_boats/templates/boats1.html
{% load static %}

<head>
    <meta charset="utf-8"/>
    <title>Marquage du texte</title>
    <!--<link rel="stylesheet" type="text/css" href="mystyle.css">-->
    <link rel="stylesheet" type="text/css" href="{% static "mystyle.css" %}">

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
</head>


<body>
<head>
    <meta charset="utf-8"/>
    <title>Marquage du texte</title>
    <!--<link rel="stylesheet" type="text/css" href="mystyle.css">-->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
</head>


<body>
<div class="container-fluid">
    <div class="row">
        <div id="control" class="col-sm-2">
            <p>Saisissez votre itinéraire</p>
            <p>
                <label for="depart">Départ</label> <input type="text" name="depart" id="depart" value="10,20"
                                                          placeholder="long,lat"/>
                <label for="destination">Destination</label> <input type="text" name="destination" id="destination"
                                                                    placeholder="34.65,78.59" value="30,10"/>
                <input type="button" id="getPath" value="get Path !"/>
                <input type="button" id="plotPathButton" value="plot"/>
            </p>
            <p id="path"> Valeur </p>
        </div>
        <div id="map" class="col-sm-10">
            ICI
        </div>
    </div>
</div>
<p id="weight"></p>


<!--<script src="submit.js"></script>-->
<!--<script src="plotEarth.js"></script>-->
<script src="{% static "submit.js" %}"></script>
<script src="{% static "plotEarth.js" %}"></script>
<script type="text/javascript"
        src="https://maps.googleapis.com/maps/api/js?key=AIzaSyC6tbOtfZnnmhsm3sqz_FMrZAg5jtX5F3c&libraries=visualization&callback=initMap"></script>
</body>

boats/app_boats/templates/map.html
{% load static %}

<head>
    <meta charset="utf-8" />
    <title>Main Page</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link href="https://gitcdn.github.io/bootstrap-toggle/2.2.2/css/bootstrap-toggle.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.12.4/css/bootstrap-select.min.css">
    <link href='http://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet'  type='text/css'>
    <link rel="stylesheet" type="text/css" href="{% static "mystyle.css" %}">

</head>


<div class="box">

    <body>


    <div class="row">
        <div id="control" class="col-sm-2">
            <a href='#' > <img src="{% static "cls.jpg" %}"  class="img-rounded" alt="Cls image" id="clsImg"> </a>
            <div class="box text-center">
                <p><strong><a href="{% url "login:settings" %}">Settings</a></strong>
                    <strong><a href="{% url "login:logout" %}">Logout</a></strong>
                </p>
            </div>
            <div class="box">
                <h2>Get me somewhere</h2>
                <p>
                    <label for="departInput">Start</label> <br/>
                    <input type="text" name="departInput" id="departInput"  value="10,20" placeholder="long,lat" /> <br/>
                    <label for="destinationInput" >End</label> <br/>
                    <input type="text" name="destinationInput" id="destinationInput" placeholder="34.65,78.59"  value="30,10"/>
                    <input type="checkbox" data-toggle="toggle"  data-on="shortest" data-off="safer" id="astarOption">
                    <input type="button" id="getPath" value="get Path !" class="btn btn-primary"/>
                    <button type="button" class="btn btn-danger" id="clearMapButton">
                        <span class="glyphicon glyphicon-trash"></span>
                    </button>
                    <!--                        <input type="button" id="plotPathButton" value="plot it !" class="btn btn-primary" />-->
                </p>
            </div>
            <div class="box" id="alert">
                <a  data-toggle="collapse" href="#collapseAlert" aria-expanded="true">
                    <h2>Send an Alert</h2>
                </a>
                <div class="collapse" id="collapseAlert" data-collapsed="false">
                    <form id="alertForm" name="alertForm">
                        <p>
                            <input type="text" name="alertPositionInput" id="alertPositionInput"  placeholder="long,lat" /> <br/>
                            <textarea name="commentary" id="commentary" placeholder="Commentary"></textarea>
                            <select name="typeAlerte" id="typeAlerte" class="selectpicker" data-width="50%">
                                <option value="optionPirate">Pirates</option>
                                <option value="optionTsunami">Tsunami</option>
                                <option value="optionIceberg">Iceberg</option>
                                <option value="optionMeteo">Weather</option>
                                <option value="optionSOS">SOS</option>
                            </select> <br/>
                            <input type="button" id="sendAlertButton" value="Send it !" class="btn btn-danger"/>
                        </p>
                    </form>

                </div>
            </div>
            <div class="box text-center" id="filtres">
                <a  data-toggle="collapse" href="#collapseFilter" aria-expanded="true">
                    <h2>Display Filters</h2>
                </a>
                <div class="collapse" id="collapseFilter">
                    <input type="checkbox" data-toggle="toggle" data-style="ios" data-on="on" data-off="off" id="displayFilter">
                    <select multiple class="form-control" id="multipleSelect">
                        <option id="optionPirate">Pirate</option>
                        <option id="optionTsunami">Tsunami</option>
                        <option id="optionIceberg">Iceberg</option>
                        <option id="optionMeteo">Weather</option>
                        <option id="optionSOS">SOS</option>

                    </select>
                </div>
            </div>

            <div class="box text-center" id="heatmap">
                <a  data-toggle="collapse" href="#collapseHeatmap" aria-expanded="true">
                    <h2>Show Density</h2>
                </a>
                <div class="collapse" id="collapseHeatmap">
                    <select name="typeAlerte" id="typeHeatMap" class="selectpicker" data-width="40%">
                        <option value="optionPirate">Pirates</option>
                        <option value="optionTsunami">Tsunami</option>
                        <option value="optionIceberg">Iceberg</option>
                        <option value="optionMeteo">Weather</option>
                        <option value="optionSOS">SOS</option>
                    </select>
                    <input type="checkbox" data-toggle="toggle" data-style="ios" data-on="on" data-off="off" id="displayHeatmap">
                    <br/>
                </div>
            </div>

            <div class="box" id="meteo">
                <h2>Weather Information</h2>
            </div>
        </div>
        <div id="map" class="col-sm-10">
        </div>
    </div>
    <!--        Bootstrap JS and Jquery ( JS need JQuery ) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <script src="http://netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>
    <!--Bootstrap Toggle Button-->
    <script src="{% static "config.js" %}"></script>
        <!--<script src="conf.js"></script>-->
    <script src="https://gitcdn.github.io/bootstrap-toggle/2.2.2/js/bootstrap-toggle.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.12.4/js/bootstrap-select.min.js"></script>
    <script src="{% static "submit.js" %}"></script>
        <!--<script src="submit.js"></script>-->
    <script src="{% static "plotEarth.js" %}"></script>
        <!--<script src="plotEarth.js"></script>-->
    <!--Google Map Script-->
    <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyC6tbOtfZnnmhsm3sqz_FMrZAg5jtX5F3c&libraries=visualization&callback=initMap"></script>
    <script src="{% static "weather.js" %}"></script>
        <!--<script src="weather.js"></script>-->
    <script src="{% static "clickOnMap.js" %}"></script>
        <!--<script src="clickOnMap.js"></script>-->
    <script src="{% static "displayFilter.js" %}"></script>
        <!--<script src="displayFilter.js"></script>-->
    <script src="{% static "displayHeatmap.js" %}"></script>

    <script type="text/javascript">
            var userName = "{{user}}";
        </script>


    </body>