boats/app_boats/urls.py
from django.conf.urls import url, include
from . import views

urlpatterns = [
    url('getPath', views.getPath),
    url(r'^$', views.BoatsView, name='boats'),
]

boats/boats/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.apps import apps
login_name = apps.get_app_config('login').verbose_name
app_boats_name = apps.get_app_config('app_boats').verbose_name
alerts_name = apps.get_app_config('app_alerts').verbose_name

urlpatterns = [
    url(r'^', include(('login.urls', login_name), namespace='login')),
    url(r'^boats', include(('app_boats.urls', app_boats_name), namespace='app_boats')),
    url(r'alerts/', include(('app_alerts.urls', alerts_name), namespace='app_alerts'))
]

boats/login/urls.py
from django.contrib.auth import views as auth_views
from django.views.generic.base import TemplateView
from django.conf.urls import url
from django.contrib import admin
from login import views

urlpatterns = [
    url(r'^$', views.homepage, {'template_name':'home.html'}, name='home'),
    url(r'home^$', views.homepage, {'template_name':'home.html'}, name='home'),
    url(r'^signup/$', views.signup, name='signup'),
    url(r'^login/$', views.custom_login, {'template_name': 'login.html'}, name='login'),
    url(r'^logout/$', auth_views.logout, {'template_name': 'logged_out.html'}, name='logout'),
    url(r'^settings/$', views.modify_user,  name='settings'),
    url(r'^change_password$',
        auth_views.password_change,
        {'template_name':'change_password.html',
            'post_change_redirect':'login:password_reset_done'},
        name='change_password'),
    url(r'^password_reset_done/$',
        TemplateView.as_view(template_name='password_reset_done.html'),
        name='password_reset_done'),
]

boats/login/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    first_name = models.TextField(max_length=30, blank=True)
    last_name = models.TextField(max_length=30, blank=True)
    email = models.EmailField(max_length=254, blank=True)
    gender = models.TextField(max_length=30, blank=True)
    bio = models.TextField(max_length=500, blank=True)
    location = models.CharField(max_length=30, blank=True)
    birth_date = models.DateField(null=True, blank=True)

@receiver(post_save, sender=User)
def update_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)
    instance.profile.save()

boats/login/forms.py
from django import forms
from django.contrib.auth import password_validation
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth.models import User
from login.models import Profile

GENDER_CHOICES = ((' ', ' '), ('NA', '--'),
        ('Male', 'Male'), ('Female', 'Female'),
        ('Non-binary', 'Non-binary'), ('Pangender', 'Pangender'),
        )

class SignUpForm(UserCreationForm):
    # Fields that will be saved into auth.User and login.Profile
    email = forms.EmailField(max_length=254,
                             help_text='Required. Inform a valid email address.')
    first_name = forms.CharField(max_length=30,
                                 required=False,
                                 help_text='Optional.')
    last_name = forms.CharField(max_length=30,
                                required=False,
                                help_text='Optional.')
    # Fields that will be saved ONLY into login.Profile
    gender = forms.ChoiceField(choices = GENDER_CHOICES,
                                required=False,
                                label = 'Gender',
                                widget=forms.Select(attrs={'style':'width:150px;'}),
                                help_text = 'Optional',
                                )
    birth_date = forms.DateField(required=False,
                                 help_text='Optional. Format: YYYY-MM-DD')
    bio = forms.CharField(max_length=1000,
                          required=False,
                          widget=forms.Textarea(attrs={'style': 'width:250px; height:150px'}),
                          help_text='Optional. Tell us more about yourself\
                                  (e.g. Credit Card Number, Social Security Number etc.)')

    class Meta:
        model = User
        fields = ('username', 'email', 'first_name', 'last_name',
                 'gender', 'birth_date', 'bio', 'password1', 'password2', )


class ModifyInfoForm(forms.Form):
    # Fields that will be saved into auth.User and login.Profile
    email = forms.EmailField(max_length=254,
                             required=False,
                             help_text='Inform a valid email address.')
    first_name = forms.CharField(max_length=30,
                                 required=False)
    last_name = forms.CharField(max_length=30,
                                required=False)
    # Fields that will be saved ONLY into login.Profile
    gender = forms.ChoiceField(choices = GENDER_CHOICES, 
                                required=False,
                                label = 'Gender',
                                widget=forms.Select(attrs={'style':'width:150px;'}),
                                help_text = 'Optional',)
    birth_date = forms.DateField(required=False,
                                 help_text='Format: YYYY-MM-DD' )
    bio = forms.CharField(max_length=1000,
                          required=False,
                          widget=forms.Textarea(attrs={'style': 'width:250px; height:150px'}),
                          help_text='Tell us more about yourself\
                                  (e.g. Credit Card Number, Social Security Number etc.)')
    class Meta:
        model = User
        fields = ('email', 'first_name', 'last_name',
                'gender', 'birth_date', 'bio','password', 'newpassword1', 'newpassword2')

boats/login/views.py
from django.contrib.auth import login, authenticate
from django.contrib.auth.forms import UserCreationForm
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from login.forms import SignUpForm, ModifyInfoForm
from django.http import HttpResponseRedirect
from django.urls import reverse

def custom_login(request, template_name):
    _message = 'Please sign in'
    if request.method == 'POST':
        _username = request.POST['username']
        _password = request.POST['password']
        user = authenticate(username=_username, password=_password)
        if user is not None:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('app_boats:boats'))
            else:
                _message = 'Your account is not activated'
        else:
            _message = 'Invalid login, please try again.'
    context = {'message': _message}
    return render(request, template_name, context)

def signup(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            user = form.save() # automatically save username, password,
                               # mail, last_name and first_name
            user.refresh_from_db()  # load the profile instance created by the signal
            user.profile.email = form.cleaned_data.get('email')
            user.profile.last_name = form.cleaned_data.get('last_name')
            user.profile.first_name = form.cleaned_data.get('first_name')
            user.profile.gender = form.cleaned_data.get('gender')
            user.profile.birth_date = form.cleaned_data.get('birth_date')
            user.profile.bio = form.cleaned_data.get('bio')
            user.save()
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=user.username, password=raw_password)
            login(request, user)
            return redirect('app_boats:boats')
    else:
        form = SignUpForm()
    return render(request, 'signup.html', {'form': form})

@login_required
def modify_user(request):
    # TODO implement the username and password modification
    # in django.contrib.auth there might be a Password Reset form
    if request.method == 'POST':
        form = ModifyInfoForm(request.POST)
        if form.is_valid():
            user = request.user
            user.refresh_from_db()  # load the profile instance created by the signal
            email = form.cleaned_data.get('email')
            last_name = form.cleaned_data.get('last_name')
            first_name = form.cleaned_data.get('first_name')
            gender = form.cleaned_data.get('gender')
            print(gender)
            birth_date = form.cleaned_data.get('birth_date')
            bio = form.cleaned_data.get('bio')
            if email != '':
                user.profile.email = email
                user.email = email
            if last_name != '':
                user.profile.last_name = last_name
                user.last_name = last_name
            if first_name != '':
                user.profile.first_name = first_name
                user.first_name = first_name
            if gender != ' ':
                user.profile.gender = gender
            if birth_date != None:
                user.profile.birth_date = birth_date
            if bio != '':
                user.profile.bio = bio
            user.save()
            return redirect('login:settings')
    else:
        form = ModifyInfoForm()
    return render(request, 'settings.html', {'form': form})

def homepage(request, template_name):
    return render(request, template_name=template_name)

boats/login/templates/base.html
{% load static %}
<html lang="en">
<head>
  <title>Boats</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" type="text/css" href="{% static "theme.css" %}">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <link href="https://fonts.googleapis.com/css?family=Lato" rel="stylesheet" type="text/css">
  <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet" type="text/css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>

<body id="myPage" data-spy="scroll" data-target=".navbar" data-offset="90">

<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="{% url 'login:home' %}">Boats</a>
    </div>
    <div id="myNavbar" class="collapse navbar-collapse">
      {% if request.path == "/" or request.path == "/home" %}
	  <ul class="nav navbar-nav navbar-left">
	    <li><a href="#team">TEAM</a></li>
	    <li><a href="#stack">STACK</a></li>
	  </ul>
      {% endif %}
      {% if user.is_authenticated %}
	  <p class="navbar-text">Hi {{ user.username }}!</p>
      {% endif %}
      <ul class="nav navbar-nav navbar-right">
	{% if user.is_authenticated %}
	    <li><a href="{% url 'app_boats:boats' %}">MAP</a></li>
	    <li><a href="{% url 'login:settings' %}">SETTINGS</a></li>
	    <li><a href="{% url 'login:logout' %}">LOGOUT</a></li>
	{% else %}
	    <li><a href="{% url 'login:login' %}" class="glyphicon glyphicon-user">LOGIN</a></li>
	    <li><a href="{% url 'login:signup' %}" class="glyphicon glyphicon-log-in"> SIGN UP</a></li>
	{% endif %}
        <!--<li><a href="#"><span class="glyphicon glyphicon-search"></span></a></li> TODO -->
      </ul>
    </div>
  </div>
</nav>
<!--This line is pushing stuff downward-->
<div class="row">
    <div class="col-sm-12">
	<p>Don't read this   <p/>
    <div/>
<div/>
{% block content %}
{% endblock %}

<div class="row">
    <div class="col-sm-12">
	<br/><br/>
    <div/>
<div/>

<!-- Footer -->
<footer class="text-right navbar-fixed-bottom">
    <strong>Contact : </strong><a href="mailto:lelonque@etud.insa-toulouse.fr">lelonque@etud.insa-toulouse.fr</a>
</footer>


    </body>
</html>

boats/login/templates/change_password.html
{% extends 'base.html' %}

{% block title %}Change Password{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
	<div class="col-sm-2">
	    <p>   </p>
	</div>
	<div class="col-sm-8">
	    <div class="jumbotron">
	    <h2>Change Password</h2>
	    <form method="post">
		{% csrf_token %}
		{{ form.as_p }}
		<div class="wrapper">
		    <button type="submit" class="btn btn-md btn-warning ">Save changes</button>
		</div>
	    </form>
	    </div>
	</div>
	<div class="col-sm-2">
	    <p>   </p>
	</div>
    </div>
</div> <!-- /container -->
{% endblock %}

boats/login/templates/home.html
{% extends 'base.html' %}

{% load static %}

{% block title %}Homepage{% endblock %}

{% block content %}
<div id="myCarousel" class="carousel slide" data-ride="carousel">
    <!-- Indicators -->
    <!--<ol class="carousel-indicators">-->
      <!--<li data-target="#myCarousel" data-slide-to="0" class="active"></li>-->
      <!--<li data-target="#myCarousel" data-slide-to="1"></li>-->
      <!--<li data-target="#myCarousel" data-slide-to="2"></li>-->
    <!--</ol>-->

    <!-- Wrapper for slides -->
    <div class="carousel-inner" role="listbox">
      <div class="item active">
	  <img src="{% static "img/home/rotterdam.png" %}" alt="Chart paths" width="1200" height="700">
        <div class="carousel-caption">
          <h3>Chart paths</h3>
          <p>Find your way through the globe.</p>
        </div>
      </div>

      <div class="item">
        <img src="{% static "img/home/suez.png" %}" alt="Receive Alerts" width="1201" height="700">
        <div class="carousel-caption">
          <h3>Receive Alerts</h3>
          <p>Might be pirates on the road.</p>
        </div>
      </div>

      <div class="item">
        <img src="{% static "img/home/img2.png" %}" alt="Check the weather" width="1200" height="700">
        <div class="carousel-caption">
          <h3>Check the weather</h3>
          <p>Nobody want to get stuck under the rain.</p>
        </div>
      </div>
    <!-- Left and right controls -->
    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
      <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
      <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
</div>

<!-- Container (The Band Section) -->
<div id="team" class="container-fluid bg-1 text-center">
  <h3>THE TEAM</h3>
  <p><em>We love to code!</em></p>
  <p>Your satisfaction comes first whenever you use our product. That's why we selected only the best suited for the task.</p>
  <br>
  <div class="row">
    <div class="col-sm-4">
      <p class="text-center"><strong>Laetitia Dufau</strong></p><br>
      <img src="{% static "img/profilepic/laetitia.jpg" %}" class="img-rounded person" alt="Random Name" width="150" height="150">
      <p>Backend developper</p>
      <p>In love with Neo4J and Proxmox</p>
      <p><a href="mailto:ldufau@etud.insa-toulouse.fr">ldufau@etud.insa-toulouse.fr</a></p>
    </div>
    <div class="col-sm-4">
      <p class="text-center"><strong>Guillaume Grasa</strong></p><br>
      <img src="{% static "img/profilepic/grasa.jpg" %}" class="img-rounded person" alt="Random Name" width="150" height="150">
      <p>Backend developper</p>
      <p>Friend of Cassandra and Neo4J</p>
      <p><a href="mailto:ggrasa@etud.insa-toulouse.fr">ggrasa@etud.insa-toulouse.fr</a></p>
    </div>
    <div class="col-sm-4">
      <p class="text-center"><strong>Thibaut Sarion</strong></p><br>
      <img src="{% static "img/profilepic/thibaut.jpg" %}" class="img-rounded person" alt="Random Name" width="150" height="150">
      <p>Front End Developper</p>
      <p>Master of Javascript</p>
      <p><a href="mailto:sarion@etud.insa-toulouse.fr">sarion@etud.insa-toulouse.fr</a></p>
    </div>
  </div>
  <br/>
  <div class="row">
    <div class="col-sm-4">
      <p class="text-center"><strong>Bastien Bigué</strong></p><br>
      <img src="{% static "img/profilepic/bastien.jpg" %}" class="img-rounded person" alt="Random Name" width="150" height="150">
      <p>Back End developper</p>
      <p>Plays with Maths and Neo4J</p>
      <p><a href="mailto:bigue-co@etud.insa-toulouse.fr">bigue-co@etud.insa-toulouse.fr</a></p>
    </div>
    <div class="col-sm-4">
      <p class="text-center"><strong>Louis Rivière</strong></p><br>
      <img src="{% static "img/profilepic/louis.jpg" %}" class="img-rounded person" alt="Random Name" width="150" height="150">
      <p>Back End developper</p>
      <p>Spark and Cassandra have no secrets for him</p>
      <p><a href="mailto:lriviere@etud.insa-toulouse.fr">lriviere@etud.insa-toulouse.fr</a></p>
    </div>
    <div class="col-sm-4">
      <p class="text-center"><strong>Léo Le Lonquer</strong></p><br>
      <img src="{% static "img/profilepic/leo.jpg" %}" class="img-rounded person" alt="Random Name" width="150" height="150">
      <p>Ultimate Front End developper</p>
      <p>PhD in CSS and HTML</p>
      <p><a href="mailto:lelonque@etud.insa-toulouse.fr">lelonque@etud.insa-toulouse.fr</a></p>
    </div>
  </div>
</div>


<div id="stack" class="container-fluid text-center">
    <h3> Our Stack </h3>
    <div class="row">
	<div class= col-sm-4>
	    <h4>Front End</h4>
	    <div class="jumbotron">
		<img src={% static "img/stack/css.png" %} class="img-responsive">
		<h4> HTML5 And CSS </h4>
		<br/>
		<img src={% static "img/stack/bootstrap.png" %} class="img-responsive">
		<h4>Bootstrap </h4>
		<br/>
		<img src={% static "img/stack/javascript.png" %} class="img-responsive">
		<h4>Javascript</h4>
		<br/>
		<img src={% static "img/stack/ajax.png" %} class="img-responsive">
		<h4>Ajax</h4>
	    </div>
	</div>
	<div class= col-sm-4>
	    <h4>Interfaces</h4>
	    <div class="jumbotron">
		<img src={% static "img/stack/python.png" %}
	  class="img-responsive text-center" style="width:80%">
		<h4>Python</h4>
		<br/>
		<img src={% static "img/stack/django.png" %} class="img-responsive">
		<h4>Django</h4>
		<br/>
		<img src={% static "img/stack/flask.png" %} class="img-responsive">
		<h4>Flask</h4>
	    </div>
	</div>
	<div class= col-sm-4>
	    <h4>Back End</h4>
	    <div class="jumbotron">
		<img src={% static "img/stack/neo4J.png" %} class="img-responsive">
		<h4>Neo4J</h4>
		<br/>
		<img src={% static "img/stack/spark.png" %} class="img-responsive">
		<h4>Spark</h4>
		<br/>
		<img src={% static "img/stack/cassandra.png" %} class="img-responsive">
		<h4>Cassandra</h4>
	    </div>
	</div>
    </div>
</div>

{% endblock %}

boats/login/templates/logged_out.html
{% extends 'base.html' %}

{% block title %}See you!{% endblock %}

{% block content %}
<div class="container text-left">
    <div class="jumbotron">
      <h2>Logged out</h2>
      <p>You have been successfully logged out.</p>
	<a type="submit" class="btn btn-md btn-primary" href="{% url 'login:login'%}">Login Again</a>
    </div>
</div>
{% endblock %}

boats/login/templates/login.html
{% extends 'base.html' %}

{% block title %}Login{% endblock %}

{% block content %}
{% load staticfiles %}
<div class="container">
    <div class="jumbotron">
      <form class="form-signin" action="{% url 'login:login' %}" method="post" id="login-form">
	  {% csrf_token %}
        <h2 class="form-signin-heading">{{ message }}</h2>
        <label for="id_username" class="sr-only">Email address</label>
        <input type="text" name="username" id="id_username" class="form-control" placeholder="User Name" required autofocus>
	<br/>
        <label for="id_password" class="sr-only">Password</label>
        <input type="password" name="password" id="id_password" class="form-control" placeholder="Password" required>
        <div class="checkbox">
          <label>
            <input type="checkbox" value="remember-me"> Remember me
          </label>
        </div>
        <button class="btn btn-lg btn-success" type="submit">Sign in</button>
      </form>
    </div>
</div> <!-- /container -->
 
<!--<script src="{% static "bootstrap/js/bootstrap.js" %}"></script>-->
{% endblock %}

boats/login/templates/password_reset_done.html
{% extends 'base.html' %}

{% block title %}Password succefuly modified{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
	<div class="col-sm-2">
	    <p>   </p>
	</div>
	<div class="col-sm-8">
	    <div class="jumbotron">
    <h2>Password successfuly modified !</h2>
    <strong><a href="{% url 'login:settings' %}">Back</a></strong>
	    </div>
	</div>
	<div class="col-sm-2">
	    <p>   </p>
	</div>
    </div>
</div> <!-- /container -->
{% endblock %}

boats/login/templates/settings.html
{% extends 'base.html' %}

{% block title %}User Settings{% endblock %}

{% block content %}
<div class="container text-left">
    <h2>User Settings</h2>
    <div class="jumbotron">
	<div class="row">
	    <div class="col-sm-6 text-left">
	<p><strong> Username :  </strong> {{user.username}}</p>
	<p><strong> Email :     </strong> {{user.email}}</p>
	<p><strong> First name :</strong> {{user.first_name}}</p>
	    </div>
	    <div class="col-sm-6 text-left">
	<p><strong> Last name : </strong> {{user.last_name}}</p>
	<p><strong> Gender: </strong> {{user.profile.gender}}</p>
	<p><strong> Birth date :</strong> {{user.profile.birth_date}}<p/>
	    </div>
	</div>
	<p><strong> Bio :       </strong> {{user.profile.bio}}</p>
    </div>
    <div class="jumbotron">
	<form method="post">
	{% csrf_token %}
	{% for field in form %}
	<div class="row">
	    <div class="col-sm-4 text-right">
		<p>{{ field.label_tag |safe}} </p>
	    </div>
	    <div class="col-sm-4 text-center">
		<p>{{ field }}</p>
		<p style="color:Tomato text-left">{{ field.errors |escape}}</p>
	    </div>
	    <div class="col-sm-4 text-left">
		<p>{{ field.help_text | safe|escape}}</p>
	    </div>
	</div>
	{% endfor %}
	<div class="wrapper">
	    <button type="submit" class="btn btn-md btn-warning ">Save changes</button>
	</div>
	</form>
	<div class="wrapper">
	<a type="submit" class="btn btn-md btn-primary" href="{% url 'login:change_password'%}">Change password</a>
	</div>
    </div>
</div>
{% endblock %}

boats/login/templates/signup.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <div class="jumbotron">
	<h2>Sign up</h2>
	<form method="post">
	    {% csrf_token %}
	    {% for field in form %}
	    <div class="row">
		<div class="col-sm-4 text-right">
		    <p>{{ field.label_tag |safe}} </p>
		</div>
		<div class="col-sm-4 text-center">
		    <p>{{ field }}</p>
		    <p style="color:Tomato text-left">{{ field.errors |escape}}</p>
		</div>
		<div class="col-sm-4 text-left">
		    <p>{{ field.help_text | safe|escape}}</p>
		</div>
	    </div>
	    {% endfor %}
	    <button class="btn btn-lg btn-success btn-block" type="submit">Sign Up</button>
	</form>
    </div>
</div>
{% endblock %}